dist: xenial
language: python
python:
  - 3.6
  - 3.7

env:
  global:
    - CC_TEST_REPORTER_ID=21357f35f0a0f044a036d38f1a2896a8e03c37e484ee3c43a3020277d363f172

before_install:
  - pip install poetry

install:
  - poetry install

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - poetry run pytest --workers auto --cov=psmon --cov-report term-missing

after_script:
  - coverage xml
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" && "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT; fi
